### PR TITLE
Added version check and fixed configureAgent procedure

### PR DESCRIPTION
**Pull request by justnoxx**

### CODE REVIEW

**Comment by aavinashjha** [comment]
Will it not be better to call only that specific procedure, instead of including entire preamble.pl ? We have done this at many places, will it not have performance issues?

**Comment by justnoxx** [comment]
It is not a call. It is just simple code inclusion. We need this check to make sure that our plugin is able to work with puppet. Anyway, perform puppet --version and check it's output is much faster than run one more EC procedure.

**Comment by aavinashjha** [comment]
Yes understood, it is not a call but a code inclusion. But it increases size of each procedure code.

**Comment by urvashisingh** [comment]
Including common code through a script snippet is a standard pattern for reusing code in plugins. Though we should be cognizant of the fact that if misused, this can increase the procedure size in most cases this does not have any measurable overhead.

**Pull request merged**
